### ISSUE TITLE
Migrating Guides to New Repo

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/guides#139]
### Overview
We need to move all existing guides to the new repository for 

### Action Items
- Set up new repo & google drive
- Add labels and milestones to new repo
- Create a form for people currently working on guides to maintain their assignment & receive access to the google drive
- Migrate guides from CoPs to boards
- Migrate guide documentation from CoP drives to Guides drive
- Inform anyone currently working on a guide of the shift

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by edwardsarah** [comment]
List of Issues to Check Post-Transition:
- [x] https://github.com/hackforla/guides/issues/48
- [x] https://github.com/hackforla/guides/issues/57
- [x] https://github.com/hackforla/guides/issues/59
- [x] https://github.com/hackforla/guides/issues/70

**Comment by edwardsarah** [comment]
## Notes about Migrating Guide Issues from CoPs to Knowledgebase-content

[Github Doc - Transferring an Issue to Another Repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository)
- from this doc, it looks like we won't have the issue we assumed we would have with losing references to the original issue. The link will just redirect
- If someone references the issue by name or issue number, they can look it up in the guides audit spreadsheet, which we can preserve
- Assignments will be preserved. Still a good idea to check in with assignees so they know what's going on, and can be removed if they are no longer working on their guide. 

Greater issue: migrating all of the associated documents
- How big of a problem is this?
- Potential roadblock is permission to view necessary files. Would likely need an additional way to track which documents cannot be migrated and how to manage that

**Comment by edwardsarah** [comment]
# Migrate product guides from CoPs to knowledgebase-content
Checklist for Moving a Guide
### Before Moving

In the guide issue you are going to move
- [ ] Copy all of the content from the body of the issue into a new comment on the same issue
- [ ] Replace the body with the new template text for guide issues
   ```
   ### Overview
   We need to create a guide to using size labels so teams can accurately assess how long tasks should take to complete.

   ### Action Items
   The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labelled 'Tasks' at the bottom of this issue, and complete each task listed.
   - [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
   - [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
   - [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
      - [ ]  If needed, create a template
   - [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
   - [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
   ### Resources/Instructions
  ### Projects to Check
  ### Tasks
   - [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
   ```
- [ ] Screenshot the labels and its current project board info
    -  Example:  
<img width="200" alt="Screenshot 2024-03-15 at 12 42 04 PM" src="https://github.com/hackforla/guides/assets/64277558/8da348b1-59ad-4647-ad20-8f69aa0c9da1">

    - [ ] Add this screenshot in another comment
- [ ] Identify all documents created for this guide issue and add them to a comment
     - [ ] Check each document for relevance (briefly - is there content in them, and does it seem useful?)
        - [ ] If useful,  add this note
        ```
        - This document will need to be moved to the knowledgebase-content Google Drive
        ```
     - [ ] If documents cannot be opened 
        - [ ] and the document exists (don't ask for write access), include the link in your comment and this note
        ```
        - Unable to view this document while moving this issue
        ```
        - [ ] and the document dosen't exist, include the link in your comment and this note
        ```
        - This document looks like it has been deleted
        ```
- [ ] If someone is currently assigned to the issue, @ them in a comment with this note
```
This guide issue is moving to the knowledgebase-content repo. If you would like to maintain access, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69). 
```
- [ ] Move the guide to the knowledgebase-content repo
    - [ ] Click Transfer Issue (see image below)
    - [ ] Choose a repository -> knowledgebase-content
    - [ ] Transfer issue
    - This may take a few minutes to complete! 
<img width="1240" alt="Screenshot 2024-03-15 at 12 44 26 PM" src="https://github.com/hackforla/guides/assets/64277558/cb1b6c6b-f290-4fb3-b413-6b0997f59bdb">

### After Moving
- [ ] Add the correct labels
    - [ ] CoP: the CoP label should reflect the community of practice the issue was transferred from
    - [ ] Size: missing 
    - [ ] Milestone: missing
    - [ ] Phase & Status: [see below](https://github.com/hackforla/guides/issues/139#issuecomment-1972952137) 
- [ ] Add to project board
    - [ ] Most guides will be added to the Prioritized Backlog column
    - [ ] if the guide's current assignee has responded saying that they are still working on the issue, put it in 'In Progress'
    - [ ] if the guide is in the peer or leadership review stage, add to 'Ready for Review'
- [ ] Add new issue number to Guides Audit Spreadsheet in the New Issue No. column.
- [ ] Transfer any documents to the knowledgebase-content drive
    - [ ] If documents cannot be moved, make a note of this in a comment on the issue
    - [ ] Create shortcuts in relevant CoP folders

**Comment by ExperimentsInHonesty** [comment]
@edwardsarah please 
- [x] link the drive created to the resources of this issue.
- [ ] explain what we are checking these links for https://github.com/hackforla/guides/issues/139#issuecomment-1731281307
- [x] Add the link to the guides audit spreadsheet to the resources section of the issue

Also we need to define how to do the following:
   >- [ ] Pick the Guide
        - Evaluate if it's a proper guide before moving it. If it needs to be split into multiple guide issues, is not useful as a guide topic, or is a duplicate, this should be sorted out before the transition takes place. 
   >- [ ] In a comment, make note of where the guide is in the process (ex. Gather Examples Solo) so the proper labels can be added

**Comment by edwardsarah** [comment]
> explain what we are checking these links for https://github.com/hackforla/guides/issues/139#issuecomment-1731281307

There are a number of issues in the Guides team repo that refer to or are dependent on the current structure of guides, with each CoP having its own board for guides. We will need to review those issues once the guides have been migrated to make sure we close any that are no longer relevant.

**Comment by edwardsarah** [comment]
# Guidance on Picking Correct Labels

This is meant to act as a general structure for how to decide what labels a guide issue should receive. It will likely need to be updated with more specific criteria as we migrate guides and deal with edge cases. 

## Non-Guide-Specific Labels
**COP**
The CoP label should reflect the CoP that the guide issue was migrated from. If, given your best judgement, there is another CoP the guide issue is relevant to, add this as well. 
**Size**
Size labels are used here the same way they are used in other HfLA repos, and reflect how much time it will take to complete the issue.
**Milestone**
Bonnie will sort the guides by milestone. Just add the milestone: missing label

## Guide Specific Labels
Begin by checking the comment you created previously with the screenshot of the issue's previous milestones and labels. This will give you some understanding of where in the process the guide was, though it is not always perfect. 

### Phase & Status
**1 - Gather Examples Solo**
- The guide issue has no examples at all AND is a guide that requires them (status 1.1-1.4)
- The guide issue has some examples, but not from all teams (status 1.1-1.4)

**2 - Gather Examples Collaborative**
- The guide issue has examples from all teams (or notes indicating that the team has been checked and no example has been found) BUT no indication that they've talked to anyone from those teams (status 2.1)

**3 - Drafting a Guide**
- The guide issue concerns a process or practice with only one way of doing things, and so does not need examples from teams (if no draft, status 3.1)
- Examples have been gathered, but there is no guide document yet (status 3.1)
- There is a draft guide, but it is incomplete (status 3.2)
- There is a complete draft guide, but it needs reformatting (status 3.2)
- There is a draft guide, but it needs a template (status 3.3)

**4 - CoP Peer Review**
- There is a complete draft, and it is properly formatted (status 4.1)
- The owner of the guide issue has commented in the issue that it is ready for review, and a basic check of the document shows that it is a complete guide with proper formatting (status 4.1)
- Feedback has been given in a previous comment, but not incorporated into the guide document (status 4.2)

**Comment by edwardsarah** [comment]
This guide issue is moving to the knowledgebase-content repo. If you would like to maintain access, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).

**Comment by aymarmsba** [comment]
Left of at the "Add to project board" where the project board "knowledge base" specific guide tracker was not showing for me

**Comment by edwardsarah** [comment]
Moving instructions into a working document, still a work in progress at the moment:
[How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)

**Comment by edwardsarah** [comment]
Document updated with more clear instructions on labelling guide issues.

**Comment by aymarmsba** [comment]
I was not able to move any files to the knowledge base content drive since I didn't have access to move files.

**Comment by fchan218** [comment]
Date: 2024-10-04
1. Progress: Migrated 13 issues and there is approx 44 issues left to migrate 
2. Blockers: On the Excel sheet, some topics do have have issue # linked but they have links to wiki page. Will those topics need to be migrated as well? 
3. Availability: 2-3 hours/week
4. ETA: 1-2 month
5. Pictures (if necessary): None

**Comment by ExperimentsInHonesty** [comment]
@fchan218 the items with no issues to migrate, that have a wiki page, need to have an epic issue to create new guide issues and link the wiki in the resources for the person who will create the guide.  Please add reviewing the epic to our next agenda, so we can approve and move it to the prioritized backlog.

**Comment by fchan218** [comment]
Date: 2024-10-10
1. Progress: Migrated 11 issues and there is approx 32 issues left to migrate. Still need to create an epic issue to create new guide issues for the topics with wiki pages. Will work on that in the following week. 
2. Blockers: inability to move a document https://github.com/hackforla/knowledgebase-content/issues/59. Should document be copied and added to drive? 
3. Availability: 2-3 hours/week
4. ETA: before 11/1 
5. Pictures (if necessary): None

**Comment by fchan218** [comment]
### Issues that need an epic issue to create new guide issues
Check off the issues once the epic issue has been made
- [ ] 2 week inactive / Update/Remove (https://github.com/hackforla/product-management/wiki/Issue-Updates-Member-Removal)
- [ ] Milestones (https://github.com/hackforla/product-management/wiki/Milestones)
- [ ] Team Calendaring (https://github.com/hackforla/product-management/wiki/Team-Calendaring
- [ ] Mail Merge (https://github.com/hackforla/product-management/wiki/Mail-Merge)
- [ ] Add Facebook Admin (https://github.com/hackforla/product-management/wiki/Add-Facebook-Admin)
- [ ] Using Icons and Emojis in Github (https://github.com/hackforla/product-management/wiki/Icon-and-Emoji-Legend)
- [ ] Google Sheets (https://github.com/hackforla/product-management/wiki/Google-Sheets)
- [ ] SCORE (https://github.com/hackforla/product-management/wiki/score)
- [ ] Agile Ceremonies (https://github.com/hackforla/product-management/wiki/Agile-Ceremonies)

**Comment by fchan218** [comment]
### Issues that needs approval prior to migration
Check off the issues once approved
Reference: [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?gid=334170522#gid=334170522)
- [x] this issue is in website repo but is listed under product in spreadsheet: https://github.com/hackforla/knowledgebase-content/issues/105
- [x] i believe we are no longer using this? https://github.com/hackforla/knowledgebase-content/issues/106
- [x] i believe we are no longer using this? https://github.com/hackforla/knowledgebase-content/issues/104
- [x] https://github.com/hackforla/knowledgebase-content/issues/107
- [x] https://github.com/hackforla/knowledgebase-content/issues/108
- [x] https://github.com/hackforla/knowledgebase-content/issues/109
- [x] https://github.com/hackforla/knowledgebase-content/issues/110
- [x] https://github.com/hackforla/knowledgebase-content/issues/111
- [x] https://github.com/hackforla/knowledgebase-content/issues/114
- [x] Needs to be broken down into 3 different issues. should it be transferred first and then have new issues created? should i make copy of the guides and put it into separate folders? https://github.com/hackforla/knowledgebase-content/issues/117
- [x] https://github.com/hackforla/knowledgebase-content/issues/115
- [x] https://github.com/hackforla/knowledgebase-content/issues/116

**Comment by fchan218** [comment]
Issues that have been moved but needs additional assistance: 
- https://github.com/hackforla/knowledgebase-content/issues/73
   - should I make copies of the documents or shortcuts to the document in the Google drive folder? 
   - Answer: No 
- https://github.com/hackforla/knowledgebase-content/issues/75

**Comment by fchan218** [comment]
Date: 2024-10-16
1. Progress: Migrated 4 issues and there is approx 22 issues left to migrate. 
   - took a while to sort through https://github.com/hackforla/knowledgebase-content/issues/73
3. Blockers: 
   - Still need to create an epic issue to create new guide issues for the topics with wiki pages. 
      - https://github.com/hackforla/guides/issues/139#issuecomment-2408641914
   - for the documents that are unable to be moved, should the documents be copied and added to drive instead?
      - see this comment: https://github.com/hackforla/guides/issues/139#issuecomment-2417926090
   - please see these comments: 
      - https://github.com/hackforla/guides/issues/139#issuecomment-2409231529
      - https://github.com/hackforla/guides/issues/139#issuecomment-2417926090
4. Availability: 2-3 hours/week
5. ETA: before 11/1 
6. Pictures (if necessary): None

**Comment by fchan218** [comment]
There are issues under Product that do not have a current issues created, but they have a relevant wiki link. These issues need to be created in the knowledgebase content repo and the relevant wiki link needs to be mentioned in the resources 
-  https://github.com/hackforla/guides/issues/187

**Comment by fchan218** [comment]
> @fchan218 the items with no issues to migrate, that have a wiki page, need to have an epic issue to create new guide issues and link the wiki in the resources for the person who will create the guide. Please add reviewing the epic to our next agenda, so we can approve and move it to the prioritized backlog.

There are issues under Product that do not have a current issues created, but they have a relevant wiki link. These issues need to be created in the knowledgebase content repo and the relevant wiki link needs to be mentioned in the resources 
-  https://github.com/hackforla/guides/issues/187

**Comment by fchan218** [comment]
Date: 2024-10-25
1. Progress: Waiting for approval on certain issues https://github.com/hackforla/guides/issues/139#issuecomment-2409231529
3. Blockers: 
   - https://github.com/hackforla/guides/issues/139#issuecomment-2409231529
4. Availability: 2-3 hours/week
5. ETA: before 11/1 
6. Pictures (if necessary): None

**Comment by fchan218** [comment]
All guides in Product have been moved to knowledgebase content repo. 

### Guides moved
- https://github.com/hackforla/knowledgebase-content/issues/4
- https://github.com/hackforla/knowledgebase-content/issues/34
- https://github.com/hackforla/knowledgebase-content/issues/35
- https://github.com/hackforla/knowledgebase-content/issues/36
- https://github.com/hackforla/knowledgebase-content/issues/37
- https://github.com/hackforla/knowledgebase-content/issues/38
- https://github.com/hackforla/knowledgebase-content/issues/39
- https://github.com/hackforla/knowledgebase-content/issues/40
- https://github.com/hackforla/knowledgebase-content/issues/41
- https://github.com/hackforla/knowledgebase-content/issues/42
- https://github.com/hackforla/knowledgebase-content/issues/43
- https://github.com/hackforla/knowledgebase-content/issues/44
- https://github.com/hackforla/knowledgebase-content/issues/45
- https://github.com/hackforla/knowledgebase-content/issues/48
- https://github.com/hackforla/knowledgebase-content/issues/49
- https://github.com/hackforla/knowledgebase-content/issues/50
- https://github.com/hackforla/knowledgebase-content/issues/51
- https://github.com/hackforla/knowledgebase-content/issues/52
- https://github.com/hackforla/knowledgebase-content/issues/58
- https://github.com/hackforla/knowledgebase-content/issues/59
- https://github.com/hackforla/knowledgebase-content/issues/60
- https://github.com/hackforla/knowledgebase-content/issues/64
- https://github.com/hackforla/knowledgebase-content/issues/65
- https://github.com/hackforla/knowledgebase-content/issues/66
- https://github.com/hackforla/knowledgebase-content/issues/73
- https://github.com/hackforla/knowledgebase-content/issues/74
- https://github.com/hackforla/knowledgebase-content/issues/75
- https://github.com/hackforla/knowledgebase-content/issues/76
- https://github.com/hackforla/knowledgebase-content/issues/83
- https://github.com/hackforla/knowledgebase-content/issues/84
- https://github.com/hackforla/knowledgebase-content/issues/85
- https://github.com/hackforla/knowledgebase-content/issues/86
- https://github.com/hackforla/knowledgebase-content/issues/105
- https://github.com/hackforla/knowledgebase-content/issues/106
- https://github.com/hackforla/knowledgebase-content/issues/107
- https://github.com/hackforla/knowledgebase-content/issues/108
- https://github.com/hackforla/knowledgebase-content/issues/109
- https://github.com/hackforla/knowledgebase-content/issues/110
- https://github.com/hackforla/knowledgebase-content/issues/111
- https://github.com/hackforla/knowledgebase-content/issues/114
- https://github.com/hackforla/knowledgebase-content/issues/115
- https://github.com/hackforla/knowledgebase-content/issues/116
- https://github.com/hackforla/knowledgebase-content/issues/117

**Comment by fchan218** [comment]
These are the issues with label ["drive: shared with me"](https://github.com/hackforla/knowledgebase-content/issues?q=is%3Aissue%20is%3Aopen%20label%3A%22drive%3A%20shared%20with%20me%22%20label%3A%22CoP%3A%20Product%22) that have documents unable to transfer into knowledgebase content drive
