### ISSUE TITLE
Epic: Research Issue Templates

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#141]
### Overview
We need to create research template issues, so that we can setup all our research projects

### Action Items
- [ ] Create the following issues
  - [ ] Research  Issue Template: Roadmap
  - [ ] Research  Issue Template: Setup Structure
  - [ ] Research  Issue  Template:  Create Roadmap Details
  - [ ] Research  Issue  Template:  Research Plan
  - [ ] Research  Issue  Template:  Research Update
  - [ ] Research  Issue  Template:  Research: Create Interview Roll Call and Session Table

### Resources/Instructions
Location of another project's issue templates we can copy from to start: https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates

**Comment by ExperimentsInHonesty** [comment]
- [x] copy the text below this item to a new comment
 ```
## Orginal draft from Resource 1.0
```
- [x] Copy the example from Resource 1.0 (title and body) and add under the text you just pasted into the new comment and choose the `Comment` button
- [x] create a new comment
- [x] Edit the prior comment and copy everything from the prior comment into the new comment
- [x] Replace the text `## Orginal draft from Resource 1.0` with 
```
## New draft for guides project
```
- [x] save the comment
- [ ] edit the last comment to customize to this project.
- [ ] review with product
- [ ] add template to template issue gallery
