### ISSUE TITLE
Epic: Research Document Templates

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/guides#155]
### Overview
We need document templates for the Research Roadmap, Research 

### Action Items
- [ ] Create the Following Issues
   - [ ] Research Document Template: Research Roadmap
   - [ ] Research Document Template: Research Plan
   - [ ] Research Document Template: How to Use the Research Plan 
   - [ ] Research Document Template: Interview Instructions
   - [ ] Research Document Template: Interview Summary
   - [ ] Research Spreadsheet Template: Interview Rollcall Session
   - [ ] Research Spreadsheet Template: Interview Recording Tracking
   - [ ] Research Spreadsheet Template: Interview Matrix Analysis
- [ ] Copy the copy block from the resources below into the new issues

### Resources/Instructions
```
### Overview
We need to create a Guides team document template based on the Internship team's research document templates.

### Action Items
- [ ] Make a new document from Resource 1.01
- [ ] Move document to Resource 1.02
- [ ] Copy the content from the internship template (Resource 1.03) to the document you just made
- [ ] Add the document to the resources below at 2.01
- [ ] Edit to be appropriate for the Guides team
- [ ] Add the document to the UX Research Guides Templates wiki page (Resource 1.04)
- [ ] Delete the example document on the wiki page
### Resources
#### Resources for creating this issue
1.01 [Guides: Template: Report Template]
1.01 [Guides: Template: Generic Spreadsheet]
1.02 [Guides Team - Research Templates](https://drive.google.com/drive/folders/1Q7-A8TG1tU0U6N795rIQa1y3Q6pJ-xCw?usp=drive_link)
1.03
- [TWE: Template: Report Template](https://docs.google.com/document/d/16GP2QU_41dOBBadLUxEurdHh3FjzbkRMKTScr66pSIQ/)
- [TWE: Template: Research Roadmap](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/)
- [TWE: Template: Research Plan](https://docs.google.com/document/d/1SDW6n086PnSrrVSmPgQZWhlkz5_yC70vDvp7Lx7u0Wo/)
- [TWE: How to use the Research Plan template](https://docs.google.com/document/d/1Cwc0w4ZPUI8989w3jU8BW2LzLK_Tl5gHdI0VxN5ej0o/)
- [TWE: Template: Interview Instructions](https://docs.google.com/document/d/1YKJZHejAAvX19NfPh1AKC4k3CuX0nrJQq9N3BXBAB2U/)
- [TWE: Template: Interview Summary Template](https://docs.google.com/document/d/1luEGeQCJEXX3p2li4ZL7UbPa1mwjc7X0Tnxh6Yhkfr8/)
- [TWE: Template: Interview Session Roll Call Spreadsheet](https://docs.google.com/spreadsheets/d/1dmJJLaBDBiZWy4-dmdxG3XqP4OemR5aJTOScD_GsoLc/)
- [TWE: Template: Interview Recording Tracking Sheet](https://docs.google.com/spreadsheets/d/1aeUFd5tZQoJCriTzJc2L-L0KS7sXmwhveewb1dviX3I/)
- [TWE: Template: Interview Matrix Analysis](https://docs.google.com/spreadsheets/d/14oYsDizKCsGN9gxw0wAlZvrrvbSul-INAtcxlOf7row/)

1.04 [Guides: UX Research Guides Templates](https://github.com/hackforla/guides/wiki/UX-Research-Guides-Templates)
#### Resources gathered during the completion of this issue
2.01
```

**Comment by edwardsarah** [comment]
@the-techgurl can you check if you are able to access these documents? 
- Interview Matrix Analysis
- Interview Recording Tracking Sheet
- Interview Session Roll Call Spreadsheet
- Interview Summary Template
- Interview Instructions

**Comment by the-techgurl** [comment]
@edwardsarah no, I'm not able to

**Comment by ExperimentsInHonesty** [comment]
I have fixed the access issue by making the folder (anyone can view)
