### ISSUE TITLE
Research Document Template: Research Roadmap

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/guides#156]
### Overview
We need to create a Guides team document template for the Research Roadmap based on the Internship team's research document templates.

### Action Items
- [x] Make a new document from Resource 1.01
- [x] Move document to Resource 1.02
- [x] Copy the content from the internship template (Resource 1.03) to the document you just made
- [x] Add the document to the resources below at 2.01
- [x] Edit to be appropriate for the Guides team
- [x] Add the document to the UX Research Guides Templates wiki page (Resource 1.04)
- [x] Delete the example document on the wiki page
#### Resources for creating this issue
1.01 [Guides: Template: Report Template](https://docs.google.com/document/d/1OOx4Jq15Hfbum7fegxWRqSwGZbet0-Lq21gRi_o4xQ0/edit?usp=sharing)
1.02 [Guides Team - Research Templates](https://drive.google.com/drive/folders/1Q7-A8TG1tU0U6N795rIQa1y3Q6pJ-xCw?usp=drive_link)
1.03 [TWE: Template: Research Roadmap](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/)
1.04 [Guides: UX Research Guides Templates](https://github.com/hackforla/guides/wiki/UX-Research-Guides-Templates)
#### Resources gathered during the completion of this issue
2.01 [Guides: Template: Research Roadmap Template](https://docs.google.com/document/d/1k53Rut2QKrOZqJzwOSXOTp8gF9Puwpv183XuvYRTkTA/edit?usp=sharing)

**Comment by edwardsarah** [comment]
The text has been copied into the template documents from the internship team's templates. It is ready to be edited at Friday's meeting.
