### ISSUE TITLE
Title: Guides: Research Roadmap: Guide Creators

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#164]
### Overview
We need to create a research roadmap to outline all the research we will do with Guide Creators so that we can make sure we don't overlap while doing comprehensive research

### Action Items
- Add to Project Board and set up milestone
  - [ ] Under "Projects," add to the Project Management Board
  - [ ] Add milestone: 04.01 Prep for User Research of Gather examples guides
- [ ] Create a new page on the wiki for the roadmap
    - [ ] Copy the template for Research Roadmap (Resource # 1.01)
    - [ ] Click on the link for creating a new wiki page (Resource # 1.02)
      - [ ] Paste in the copied template 
      - [ ] Name it `[type name] Research Overview`
    - [ ] update the link in the resources below (Resource # 2.01)
    - [ ] link it to the Research Output Overview wiki page (Resource # 1.03)
- Create new Google Drive Folder
   - [ ] Go to the Google Drive, Research, 1. Research by Type, Folder (Resource # 1.04)
     - [ ] Create a new folder in the drive called [number. name of type] (e.g., 1. Mentor, 2. Intern)
     - [ ] update the link in the resources below (Resource # 2.02)
- [ ] Make a new document using the report template 
  - [ ] Copy the research roadmap template (Resource # 1.05)
  - [ ] Move the document from "My Drive" to the shared drive guides folder that you just created.
  - [ ] Name the document to be called Guides: Research Roadmap: [name of type] 
  - [ ] update the link in the resources below (Resource # 2.03)
- Create the research roadmap content
   - [ ] Fill out the research roadmap
   - [ ] Update the Table of contents (page 2) when you are finished with the document
- Get Approvals/Make Edits
   - [ ] UX Research Lead sign-off
   - [ ] Product-sign off

#### Resources for creating this issue
1.01 [WIKI template for Research Roadmap](https://github.com/hackforla/guides/wiki/research-roadmap-wiki-template)
1.02 [Click to create new page on wiki](https://github.com/hackforla/guides/wiki/_new)
1.03 [Research Output Overview](https://github.com/hackforla/guides/wiki/Research-Output-Overview)
1.04 [Google Drive, Research, 1. Research by Participant Type Folder](https://drive.google.com/drive/folders/1rFyhdgGs7wzGSujEzXXDDo02govPtyKV)
1.05 [Guides: Template: Research Roadmap](https://docs.google.com/document/d/1k53Rut2QKrOZqJzwOSXOTp8gF9Puwpv183XuvYRTkTA/edit?usp=sharing)

#### Resources gathered during the completion of this issue
2.01 [RP000: Wiki Page]
2.02 [Google Drive, Research, 1. Research by Type, [Number. Name of Type]]
2.03 [Guides: Template: Research Roadmap: [TYPE]]

**Comment by ExperimentsInHonesty** [comment]
@the-techgurl when we start filling out this roadmap  we will need a research plan inside the roadmap doc to evaluate how our reorg of the guides locations (moving to google drive) is landing with CoP members them (guide creators) and any additional changes we need to make to the roll out.

**Comment by ExperimentsInHonesty** [comment]
Add to the document an intake baseline (survey) that would find out how much exposure/mastery they haa
