### ISSUE TITLE
Clean Up Guide Issues for Triage

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/guides#174]
### Dependency
We need to move all the guides before this triage can happen
- [x] hackforla/guides#185
- [x] hackforla/guides#179 
- [x] hackforla/guides#180 
- [x] hackforla/guides#181 
- [x] hackforla/guides#182 
- [x] hackforla/guides#183 
- [x] hackforla/guides#184
- [x] https://github.com/hackforla/guides/issues/139
- [ ] Make sure there are no issues that still need document accessibility resolved ["drive: shared drive"](https://github.com/hackforla/knowledgebase-content/issues?q=is%3Aopen%20is%3Aissue%20label%3A%22drive%3A%20shared%20drive%22) and ["drive: shared with me"](https://github.com/hackforla/knowledgebase-content/issues?q=is%3Aopen%20is%3Aissue%20label%3A%22drive%3A%20shared%20with%20me%22)  
   - [ ] #194 
   - [ ] #189

### Overview
We need to make sure all guide issues in Knowledgebase-content are ready for the team to review and triage.

### Action Items
- [ ] For each issue in the 'Needs to Be Triaged' column of the Guides: Knowledgebase Content Tracker, follow the instructions on How to Clean Up a Guide Issue for Triage.
    - [ ] If necessary, update the body of the issue with relevant information and delete outdated resources
    - [ ] Check the folder has been created in the knowledgebase-content drive and has the necessary shortcuts
    - [ ] Hide resolved and outdated comments
    - [ ] Add the 'Ready for Bonnie Review' label when the process has been completed
- [ ] Use the template below for status updates whenever you make progress on the project.
- [ ] Leave any questions in this issue by adding a comment below
    - [ ] notify guide lead
    - [ ] If your question references a specific issue or comment on the issue, include a link to it in your comment

### Resources/Instructions

- [How to Clean Up a Guide Issue for Triage](https://docs.google.com/document/d/1oSNOINFFCzd_8lW8VhuWmlupTWn-DmeOwoW1KP9lVVE/edit?usp=sharing)
- [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)

### Template for Status Updates:
```
Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
```
