### ISSUE TITLE
Migrating Engineering Guides to New Repo

### ISSUE THREAD

**Issue by JesseTheCleric** [hackforla/guides#179]
### Overview
We need to move all existing guides to the new repository for guides and templates (knowledgebase-content)

### Prerequisite
You need to have 
- Manager access to the following drives
   - CoP Google Drives
   - KB-content drive
- Admin access for the repos the issues are in

### Action Items
Use the Guide below to migrate all guides related to Engineering from CoPs to knowledgebase-content.  (e.g., there might be a research guide that is relevant to product in the Engineering community of practice). 
- [x] Do steps 1-5
- [x] Add a comment below with the heading and add a link to each of the issues you moved for that CoP
```
### Guides that are ready to move for lead review
- #
```
- [x] Move this issue to the Questions/Review column on project board and add the label `ready for pm lead`
   - [ ] Message the lead in the Guides Slack channel by sending a link to the comment with the issues 
- [x] lead will sign-off if the issues are ready to move
   - [ ] once you get sign-off, you can move the issues (step 6 in the guide)
- [x] Check wikis/other resources for references to guides by numbers or names, so no links end up broken
- [x] When you are done, go to https://github.com/hackforla/guides/issues/174 and check off the dependency.  If all other dependencies are checked off already, then move that issue into the new issue approval column and add it to the team agenda https://github.com/hackforla/guides/issues/136

### Resources/Instructions
- Epic for all CoP guides moves: https://github.com/hackforla/guides/issues/169
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Repo [Engineering CoP Repo](https://github.com/hackforla/engineering)
  - Repo, Issue Tab: [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/engineering/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+)
     - Repo, Issue Tab, "Create a Guide" only issue [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/engineering/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+%22Create+a+Guide%2FTemplate%22)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)
- Form: [Guides Migration Google Form](https://forms.gle/LixbvxuopKthEwZo9) 
- Spreadsheet: [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?usp=sharing)
- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)

**Comment by fchan218** [comment]
### Issues that need to be checked prior to Steps 1-5 for migration into knowledgebase content repo
Check off the issues that can be migrated
- [x] https://github.com/hackforla/knowledgebase-content/issues/143
- [x] https://github.com/hackforla/knowledgebase-content/issues/148
- [x] https://github.com/hackforla/knowledgebase-content/issues/144
- [x] https://github.com/hackforla/knowledgebase-content/issues/145
- [x] https://github.com/hackforla/knowledgebase-content/issues/149
- [x] https://github.com/hackforla/knowledgebase-content/issues/150
- [x] https://github.com/hackforla/knowledgebase-content/issues/151
- [x] https://github.com/hackforla/knowledgebase-content/issues/152
- [x] https://github.com/hackforla/knowledgebase-content/issues/153
- [x] https://github.com/hackforla/knowledgebase-content/issues/154
- [x] https://github.com/hackforla/knowledgebase-content/issues/155
- [x] https://github.com/hackforla/knowledgebase-content/issues/156
- [x] https://github.com/hackforla/knowledgebase-content/issues/157
- [x] https://github.com/hackforla/knowledgebase-content/issues/158

**Comment by ExperimentsInHonesty** [comment]
This epic has one new issue which I have moved, but it will need reformatting
- [x] https://github.com/hackforla/knowledgebase-content/issues/120

**Comment by fchan218** [comment]
@JesseTheCleric I have assigned you to start working on migrating the engineering guides to knowledgebase content repo

**Comment by JesseTheCleric** [comment]
### Guides that are ready for lead review
Please check off when you have reviewed it.

- [x] https://github.com/hackforla/knowledgebase-content/issues/144
- [x] https://github.com/hackforla/knowledgebase-content/issues/145
- [x] https://github.com/hackforla/knowledgebase-content/issues/149
- [x] https://github.com/hackforla/knowledgebase-content/issues/150
- [x] https://github.com/hackforla/knowledgebase-content/issues/151

**Comment by JesseTheCleric** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the [INSERT COP NAME] Repo:</summary>
<p>


![Image](https://github.com/user-attachments/assets/24676b20-639c-493b-bc83-eadc9ff37aec)

</p>
</detail>

**Comment by JesseTheCleric** [comment]
s

**Comment by fchan218** [comment]
> ### Issues that need to be checked prior to Steps 1-5 for migration into knowledgebase content repo
> Check off the issues that can be migrated
> 
> * [x]  [Create a Guide/Template: Using Docker knowledgebase-content#143](https://github.com/hackforla/knowledgebase-content/issues/143)[x]  [Create a Guide/Template: Systems Diagram engineering#37](https://github.com/hackforla/knowledgebase-content/issues/148)[x]  [Create a Guide/Template: Interview Practice engineering#33](https://github.com/hackforla/knowledgebase-content/issues/144)[x]  [Create a Guide/Template: Documentation Technologies engineering#29](https://github.com/hackforla/knowledgebase-content/issues/145)[x]  [Create a Guide/Template: Compilation with Webpack engineering#28](https://github.com/hackforla/knowledgebase-content/issues/149)[x]  [Create a Guide/Template: Testing GitHub actions in your own repository engineering#27](https://github.com/hackforla/knowledgebase-content/issues/150)[x]  [Create a Guide/Template: Decision Records engineering#26](https://github.com/hackforla/knowledgebase-content/issues/151)[x]  [Create a Guide/Template: CI/CD with GitHub actions engineering#25](https://github.com/hackforla/knowledgebase-content/issues/152)[x]  [Create a Guide/Template: Implementing Tests with Your Code Changes engineering#19](https://github.com/hackforla/knowledgebase-content/issues/153)[x]  [Create a Guide/Template: Setting up Git engineering#16](https://github.com/hackforla/knowledgebase-content/issues/154)[x]  [Create a Guide/Template: Agile Development/Scrum/Kanban engineering#15](https://github.com/hackforla/knowledgebase-content/issues/155)[x]  [Create a Guide/Template: Professional Development engineering#14](https://github.com/hackforla/knowledgebase-content/issues/156)[x]  [Create a Guide/Template: Site Architecture Documentation engineering#3](https://github.com/hackforla/knowledgebase-content/issues/157)[x]  [Create a Guide/Template: Making a good CONTRIBUTING doc for your project's github repo engineering#2](https://github.com/hackforla/knowledgebase-content/issues/158)

@JesseTheCleric all these issues will need to be moved. please DO NOT make edits to the comment box. please make NEW comment instead.

**Comment by fchan218** [comment]
> Issues ready for Lead
> 
> * [x]  [Create a Guide/Template: Interview Practice engineering#33](https://github.com/hackforla/knowledgebase-content/issues/144)[x]  [Create a Guide/Template: Documentation Technologies engineering#29](https://github.com/hackforla/knowledgebase-content/issues/145)[x]  [Create a Guide/Template: Compilation with Webpack engineering#28](https://github.com/hackforla/knowledgebase-content/issues/149)[x]  [Create a Guide/Template: Testing GitHub actions in your own repository engineering#27](https://github.com/hackforla/knowledgebase-content/issues/150)[ ]  [Create a Guide/Template: Decision Records engineering#26](https://github.com/hackforla/knowledgebase-content/issues/151)

@JesseTheCleric 4/5 are ready for transfer. please fix the 5th one. I have made a comment on the issue on what needs to be fixed

**Comment by ExperimentsInHonesty** [comment]
@JesseTheCleric You have not added any other issues that you have reviewed.  Please finish doing the steps for the rest of the issues by Friday.

**Comment by JesseTheCleric** [comment]
### Guides that are ready for lead review
Please check off when you have reviewed it.

- [x] https://github.com/hackforla/knowledgebase-content/issues/152
- [x] https://github.com/hackforla/knowledgebase-content/issues/153
- [x] https://github.com/hackforla/knowledgebase-content/issues/154
- [x] https://github.com/hackforla/knowledgebase-content/issues/155
- [x] https://github.com/hackforla/knowledgebase-content/issues/156

**Comment by fchan218** [comment]
@JesseTheCleric 

> ### Guides that are ready for lead review
> Please check off when you have reviewed it.
> 
> * [x]  [Create a Guide/Template: CI/CD with GitHub actions engineering#25](https://github.com/hackforla/knowledgebase-content/issues/152)[ ]  [Create a Guide/Template: Implementing Tests with Your Code Changes engineering#19](https://github.com/hackforla/knowledgebase-content/issues/153)[x]  [Create a Guide/Template: Setting up Git engineering#16](https://github.com/hackforla/knowledgebase-content/issues/154)[ ]  [Create a Guide/Template: Agile Development/Scrum/Kanban engineering#15](https://github.com/hackforla/knowledgebase-content/issues/155)[x]  [Create a Guide/Template: Professional Development engineering#14](https://github.com/hackforla/knowledgebase-content/issues/156)

I've reviewed all 5. 3/5 are ready to move. Please check the comments for the 2 unchecked ones

**Comment by JesseTheCleric** [comment]
### Guides that are ready for lead review
Please check off when you have reviewed it.
- [x] https://github.com/hackforla/knowledgebase-content/issues/157
- [x] https://github.com/hackforla/knowledgebase-content/issues/158

**Comment by JesseTheCleric** [comment]
1. Progress: Steps 1-5 Complete on 13/13,  All 11 Steps complete on 2/13
2. Blockers: None 
3. Availability: 4 Hours
4. ETA: 02-21-25
5. Pictures or links : [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?gid=334170522#gid=334170522)

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni  It's been a week since you were assigned.

I spoke to France, and she indicated that the 11 issues should take about 30 min apiece to move, which would be 5.5 hours.  Given that your commitment is 20 hours a week, this work should have been turned in already so that she could give you feedback, and you could fix anything needing to be fixed, in time for her to check it again before the next meeting.  She has not heard from you, other than letting us know that you wouldn't make the meeting last week.

Please provide update on this issue. 
<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):

**Comment by Aditya23soni** [comment]
@ExperimentsInHonesty Hello Bonnie. I shall provide the updates for the issues to France today. I am working on those right now, as last week was a little occupied with the festival and travelling.
Apologies for the delay.

**Comment by Aditya23soni** [comment]
Issues that I migrated to KB @fchan218 @ExperimentsInHonesty 
The issues that are checked off have been migrated with all 13 steps completed.
- [x] https://github.com/hackforla/knowledgebase-content/issues/148
- [x] https://github.com/hackforla/knowledgebase-content/issues/149
- [x] https://github.com/hackforla/knowledgebase-content/issues/150
- [x] https://github.com/hackforla/knowledgebase-content/issues/151
- [x] https://github.com/hackforla/knowledgebase-content/issues/152
- [x] https://github.com/hackforla/knowledgebase-content/issues/153
- [x] https://github.com/hackforla/knowledgebase-content/issues/154
- [x] https://github.com/hackforla/knowledgebase-content/issues/155
- [x] https://github.com/hackforla/knowledgebase-content/issues/156
- [x] https://github.com/hackforla/knowledgebase-content/issues/157
- [x] https://github.com/hackforla/knowledgebase-content/issues/158

**Comment by Aditya23soni** [comment]
@ExperimentsInHonesty 
1. Progress: Finished migrating 11/11 Guide issues to KB. All 13 Steps done
2. Blockers: Step 9 is not functional. I am unable to assign the issues to the KB Project Board
3. Availability: 20 hrs
4. ETA: 1 DAY
5. Pictures (if necessary): 

![Image](https://github.com/user-attachments/assets/13a4e58f-ce85-4e47-b496-8a50f15cbf0c)

**Comment by fchan218** [comment]
@Aditya23soni I am unable to add the issues to the KB Tracker Project Board also. We will discuss with Bonnie during our meeting on Friday. I have checked all the issues. One needs to be addressed: https://github.com/hackforla/knowledgebase-content/issues/155#issuecomment-2732968224

**Comment by Aditya23soni** [comment]
@fchan218 This has been addressed.

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni I am unable to see what specifically you have completed on this issue, and what remains, because none of the check boxes at the top of this issue are checked off. Please update the top of the issue as well as giving a status report in a comment.

**Comment by Aditya23soni** [comment]
@ExperimentsInHonesty I have moved all 11 Engineering Guides Issues to KB Repo mentioned in the comment https://github.com/hackforla/guides/issues/179#issuecomment-2732001270
@fchan218 have validated the same.

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni please check off the checkboxes for the items that are done in the top

**Comment by Aditya23soni** [comment]
@ExperimentsInHonesty Done. And I have cleaned up the comments as well
