### ISSUE TITLE
Migrating Ops Guides to New Repo

### ISSUE THREAD

**Issue by Aditya23soni** [hackforla/guides#180]
### Overview
We need to move all existing guides to the new repository for guides and templates (knowledgebase-content)

### Prerequisite
You need to have 
- Manager access to the following drives
   - CoP Google Drives
   - KB-content drive
- Admin access for the repos the issues are in

### Action Items
Use the Guide below to migrate all guides related to UI/UX from CoPs to knowledgebase-content.  (e.g., there might be a research guide that is relevant to product in the UI/UX community of practice). 
- [x] Do steps 1-5
- [ ] Add a comment below with the heading and add a link to each of the issues you moved for that CoP
```
### Guides that are ready to move for lead review
- #
```
- [x] Move this issue to the Questions/Review column on project board and add the label `ready for pm lead`
   - [ ] Message the lead in the Guides Slack channel by sending a link to the comment with the issues 
- [x] lead will sign-off if the issues are ready to move
- [x] once you get sign-off, you can move the issue (step 6 in the guide)
- [x] Check wikis/other resources for references to guides by numbers or names, so no links end up broken
- [x] When you are done, go to https://github.com/hackforla/guides/issues/174 and check off the dependency.  If all other dependencies are checked off already, then move that issue into the new issue approval column and add it to the team agenda https://github.com/hackforla/guides/issues/136

### Resources/Instructions
- Epic for all CoP guides moves: https://github.com/hackforla/guides/issues/169
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Repo [Ops CoP Repo](https://github.com/hackforla/Ops)
  - Repo, Issue Tab: [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/ops/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+)
     - Repo, Issue Tab, "Create a Guide" only issue [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/ops/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+%22Create+a+Guide%2FTemplate%22+)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)
- Form: [Guides Migration Google Form](https://forms.gle/LixbvxuopKthEwZo9) 
- Spreadsheet: [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?usp=sharing)
- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)

**Comment by Aditya23soni** [comment]
### Guides that are ready to move for lead review
- https://github.com/hackforla/devops-security/issues/90

**Comment by ExperimentsInHonesty** [comment]
1. Progress: completed prepping 14 issues for guide creation (which is all the guides on this repo)
2. Blockers: Waiting for approval from France to move
3. Availability: Available 7 hours
4. ETA: will be able to move all the issues once blockers transferred.
5. Pictures (if necessary): N/A

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni You notified someone who was the author of the issue.  The instructions were to notify people who were assigned to the issue.  Please do not notify anyone else.

I had unassigned everyone in 2021
>@ExperimentsInHonesty ExperimentsInHonesty unassigned NivenPrasad and khushbooshah-PM on Nov 29, 2021

Your comment where you notified him
- https://github.com/hackforla/knowledgebase-content/issues/71

**Comment by ExperimentsInHonesty** [comment]
### Issues that @Aditya23soni did steps 1-5 on
check them off when approved to continue steps 6 onward

- [ ] ~https://github.com/hackforla/devops-security/issues/90~ This issue turned out not to be a guide.  I removed the label and reverted it
- [ ] ~https://github.com/hackforla/ops/issues/132~ This issue is an issue to create guides issues.  This can stay on their repo.
- [ ] ~https://github.com/hackforla/ops/issues/145~ This is am issue to create checklists which would eventually go in guides, but right now, are just being hashed out.
- [x] https://github.com/hackforla/knowledgebase-content/issues/67
- [ ] ~https://github.com/hackforla/incubator/issues/119~ specific to the incubator
- [ ] ~https://github.com/hackforla/ops/issues/71~
- [ ] ~https://github.com/hackforla/knowledgebase-content/issues/77~
- [ ] ~https://github.com/hackforla/incubator/issues/120~
- [x] https://github.com/hackforla/knowledgebase-content/issues/68
- [x] https://github.com/hackforla/knowledgebase-content/issues/69
- [x] https://github.com/hackforla/knowledgebase-content/issues/70
- [x] https://github.com/hackforla/knowledgebase-content/issues/71
- [x] https://github.com/hackforla/knowledgebase-content/issues/72
- [x] https://github.com/hackforla/knowledgebase-content/issues/82

**Comment by ExperimentsInHonesty** [comment]
The Milestones linked in the agenda are for the CoPs (https://github.com/hackforla/guides/issues/131#issuecomment-1604438478), and the KB will need all of 1-6s but the CoPs will  need 1-5, and 6-x and all the 6s will be replaced with just Guides.

**Comment by Aditya23soni** [comment]
1. Progress: Transfered 6/7 Issues to Knowledge-based Content.
2. Blockers: I was a little confused about the Status and Phase tag.
3. Availability: 6 hours.
4. ETA: Will be able to transfer all the leftover issues.
5. Pictures (if necessary): N/A

**Comment by ExperimentsInHonesty** [comment]
Issues below need to be combined
- https://github.com/hackforla/knowledgebase-content/issues/71
- https://github.com/hackforla/knowledgebase-content/issues/1

**Comment by fchan218** [comment]
### Closed Issues that need to be checked prior to migration to knowledgebase content repo: 
Check off issues that need to be moved
- [ ] ~https://github.com/hackforla/ops/issues/92~ does not need to be moved
- [ ] ~https://github.com/hackforla/ops/issues/70~ does not need to be moved
- [ ] ~https://github.com/hackforla/ops/issues/31~ does not need to be moved

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni we ended up moving this issue to kb-content after all.  All I have done is the transfer, you did copying labels etc steps before... 

- [x] can you take look now and see what is left to do https://github.com/hackforla/knowledgebase-content/issues/77

**Comment by Aditya23soni** [comment]
@ExperimentsInHonesty, I have completed the rest of the steps, and this is complete now.
https://github.com/hackforla/knowledgebase-content/issues/77

**Comment by Aditya23soni** [comment]
Date: 10/18/2024
1. Progress: Transfered all 7 Issues to Knowledge-based Content.
2. Blockers:  None.
3. Availability: 6 hours.
4. ETA: None
5. Pictures (if necessary): N/A

**Comment by ExperimentsInHonesty** [comment]
The ops repo review and moving of guides to knowlegebase-content has been completed.
- All the guides that should be moved have been.
- All other documentation issues that are not guides for people outside the DevOps team have been changed to just have the wiki label and the word guide replaced with documentation.
- link the knowlegebase-content project board to the repo

**Comment by ExperimentsInHonesty** [comment]
Do step 14 for these guides

**Comment by Aditya23soni** [comment]
Date: 11/15/2024
1. Progress: Completed step 14 for all the above guides
2. Blockers:  None.
3. Availability: 6 hours.
4. ETA: None
5. Pictures (if necessary): N/A

**Comment by ExperimentsInHonesty** [comment]
Hi @Aditya23soni Please re-review each of the issues you moved against the guide.  It seems like board status, labels, and other things don't conform to the guidance.

**Comment by Aditya23soni** [comment]
SURE BONNIE. I shall look into them today and make the necessary changes.

**Comment by Aditya23soni** [comment]
Hi @ExperimentsInHonesty , Where is the guidance mentioned? I circled back and checked some of the issues we moved against the guides to KB. I can not find the labels that don't conform to the needed guidance.

**Comment by fchan218** [comment]
hi @Aditya23soni, here is the link for the guidance: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?tab=t.0)

please go back through all the issues and make sure that they have the proper status/phase labels (step 8 of the guidance) and they are on the right project board with the correct status (step 9 of the guidance)

**Comment by fchan218** [comment]
> hi @Aditya23soni, here is the link for the guidance: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?tab=t.0)
> 
> please go back through all the issues and make sure that they have the proper status/phase labels (step 8 of the guidance) and they are on the right project board with the correct status (step 9 of the guidance)

**Comment by Aditya23soni** [comment]
@fchan218 I checked all the issues. As mentioned in the document, all the statuses in the project boards are correct. That is "needs to be triaged".
The Phase and Status labels are also according to the Figma diagram that is attached to the document. Let me know if I am missing something here.

**Comment by fchan218** [comment]
@Aditya23soni here is an example: https://github.com/hackforla/knowledgebase-content/issues/69
the status for the knowledgebase content tracker project board should be "needs to be triaged", not "prioritized backlog". also, the phase and status is wrong. there is no draft that is listed in the resources, so the phase and status should be phase 1 and status 1.1-1.4. 

please go through all the issues that are checked off and double check the phase/status labels and project boards

**Comment by fchan218** [comment]
@Aditya23soni please make the following changes: 
- there is no guide in this issue so the status and phase labels need to be changed and remove this issue from the CoP: DevOps: Project Board: https://github.com/hackforla/knowledgebase-content/issues/67
- there is a draft but it is not yet complete. change the phase and status. also change the status of the project board knowledgebase content tracker: https://github.com/hackforla/knowledgebase-content/issues/68
- change the phase and status. also change the status of the project board knowledgebase content tracker: https://github.com/hackforla/knowledgebase-content/issues/70
- change the phase and status since there is no draft: https://github.com/hackforla/knowledgebase-content/issues/72
- change the phase and status. also change the status of both project boards: https://github.com/hackforla/knowledgebase-content/issues/82

**Comment by Aditya23soni** [comment]
@fchan218 , thank you for pointing them out. I have made the necessary changes. :)

**Comment by fchan218** [comment]
@Aditya23soni please make the following changes:
- this is the wrong phase and status. should be phase 1 and status 1 because there is no guide: https://github.com/hackforla/knowledgebase-content/issues/67
- wrong phase and status: https://github.com/hackforla/knowledgebase-content/issues/70

**Comment by fchan218** [comment]
@Aditya23soni please provide update

**Comment by Aditya23soni** [comment]
@fchan218 I have made the changes. Apologies for the delay in updating.

**Comment by fchan218** [comment]
@Aditya23soni wrong phase and status: https://github.com/hackforla/knowledgebase-content/issues/70

**Comment by fchan218** [comment]
@Aditya23soni you forgot to add the rest of the status labels: https://github.com/hackforla/knowledgebase-content/issues/67

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

Please finish cleaning up the comments on the ops issue and provide a list of issues that you have done that for, in comment below

**Comment by Aditya23soni** [comment]
- https://github.com/hackforla/knowledgebase-content/issues/67
 - https://github.com/hackforla/knowledgebase-content/issues/68 (Need to ask bonnie on a comment she made in this issue before clearing it)
 - https://github.com/hackforla/knowledgebase-content/issues/69
 - https://github.com/hackforla/knowledgebase-content/issues/71 (Need Bonnie's review on a comment)
 - https://github.com/hackforla/knowledgebase-content/issues/72 (Only one comment to clean up but it has an "unable to access doc" tag)

**Comment by Aditya23soni** [comment]
Progress: Completed all the repos to add the correct "Shared with me:" labels and cleaned all the comments on Ops issues.
Blockers: None. Only a few confusions which were resolved by France.
Availability: 1 week
ETA: By today

**Comment by ExperimentsInHonesty** [comment]
@JesseTheCleric please review each of these issues to make sure all the steps have been done.
### Issues that @Aditya23soni did steps 1-14 on

- [x] https://github.com/hackforla/knowledgebase-content/issues/67
- [x] https://github.com/hackforla/knowledgebase-content/issues/68
- [x] https://github.com/hackforla/knowledgebase-content/issues/69
- [x] https://github.com/hackforla/knowledgebase-content/issues/70
- [x] https://github.com/hackforla/knowledgebase-content/issues/71
- [x] https://github.com/hackforla/knowledgebase-content/issues/72
- [x] https://github.com/hackforla/knowledgebase-content/issues/82


The steps are in 
- [ ] [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?tab=t.0)
- [ ] [How to Clean Up a Guide Issue for Triage](https://docs.google.com/document/d/1oSNOINFFCzd_8lW8VhuWmlupTWn-DmeOwoW1KP9lVVE/edit?tab=t.0)

If steps have not been done, provide the following information in a comment to @Aditya23soni 
```
@Aditya23soni 
- Issue link: 
- Steps missing from Guide
   - Move: 
   - Clean:
- notes: 
```
and put a link to your comment in a comment below on this issue

If all steps have been completed, provide this comment in the issue
```
I have checked this guide issue, and all the Moving and Cleaning steps have been completed.
```

**Comment by Aditya23soni** [comment]
@JesseTheCleric 
I have completed all the steps for Guide cleaning
- [How to Clean Up a Guide Issue for Triage](https://docs.google.com/document/d/1oSNOINFFCzd_8lW8VhuWmlupTWn-DmeOwoW1KP9lVVE/edit?tab=t.0)

for Ops, Marketing and Revenue and added Bonnie triage tag.
Ops: https://github.com/hackforla/guides/issues/180#issuecomment-2659768915
Marketing: https://github.com/hackforla/guides/issues/182#issuecomment-2408632621
Revenue: https://github.com/hackforla/guides/issues/183#issuecomment-2408631249

Kindly check them once and let me know if anything is missing.

**Comment by JesseTheCleric** [comment]
### Links to Issue Comments 
Check off when addressed 
- [x] https://github.com/hackforla/knowledgebase-content/issues/71#issuecomment-2689917738
- [x] https://github.com/hackforla/knowledgebase-content/issues/82#issuecomment-2689938018

**Comment by Aditya23soni** [comment]
@JesseTheCleric Done

**Comment by fchan218** [comment]
@Aditya23soni please check off the boxes in the description for the steps that you have completed
