### ISSUE TITLE
Migrating Marketing Guides to New Repo

### ISSUE THREAD

**Issue by JesseTheCleric** [hackforla/guides#182]
### Overview

We need to move all existing guides to the new repository for guides and templates (knowledgebase-content)

### Prerequisite
You need to have 
- Manager access to the following drives
   - CoP Google Drives
   - KB-content drive
- Admin access for the repos the issues are in

### Action Items
Use the Guide below to migrate all guides related to UI/UX from CoPs to knowledgebase-content.  (e.g., there might be a research guide that is relevant to product in the UI/UX community of practice). 
- [ ] Do steps 1-5
- [ ] Add a comment below with the heading and add a link to each of the issues you moved for that CoP
```
### Guides that are ready to move for lead review
- #
```
- [ ] Move this issue to the Questions/Review column on project board and add the label `ready for pm lead`
   - [ ] Message the lead in the Guides Slack channel by sending a link to the comment with the issues 
- [ ] lead will sign-off if the issues are ready to move
- [ ] once you get sign-off, you can move the issue (step 6 in the guide)
- [ ] Check wikis/other resources for references to guides by numbers or names, so no links end up broken
- [ ] When you are done, go to https://github.com/hackforla/guides/issues/174 and check off the dependency.  If all other dependencies are checked off already, then move that issue into the new issue approval column and add it to the team agenda https://github.com/hackforla/guides/issues/136

### Resources/Instructions
- Epic for all CoP guides moves: https://github.com/hackforla/guides/issues/169
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Repo [Marketing CoP Repo](https://github.com/hackforla/marketing)
  - Repo, Issue Tab: [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+)
     - Repo, Issue Tab, "Create a Guide" only issue [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+%22Create+a+Guide%2FTemplate%22)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)
- Form: [Guides Migration Google Form](https://forms.gle/LixbvxuopKthEwZo9) 
- Spreadsheet: [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?usp=sharing)
- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
The Milestones linked in the agenda are for the CoPs (https://github.com/hackforla/guides/issues/131#issuecomment-1604438478), and the KB will need all of 1-5s but the CoPs will  need 1-4, and 6-x and all the 5s will be replaced with just Guides.

**Comment by fchan218** [comment]
### Issues to check before proceeding with steps 1-5: 
check them off when approved to begin steps 1-5

- [ ] ~https://github.com/hackforla/marketing/issues/73~
- [x] https://github.com/hackforla/knowledgebase-content/issues/118
- [x] https://github.com/hackforla/knowledgebase-content/issues/119
- [x] https://github.com/hackforla/knowledgebase-content/issues/122

**Comment by fchan218** [comment]
@Aditya23soni 

Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by Aditya23soni** [comment]
1. Progress: Added step 14 in the previously moved Issues. Done with moving 1/3 marketing issues to KB
2. Blockers: None so far
3. Availability: 6 hours
4. ETA: EOW
5. Pictures or links* (if necessary):

**Comment by Aditya23soni** [comment]
1. Progress: Added step 14 in the previously moved Issues. Done with moving 3/3 marketing issues to KB
2. Blockers: None so far. We will close this issue during the meeting today.
3. Availability: 6 hours
4. ETA: EOW
5. Pictures or links* (if necessary):

**Comment by ExperimentsInHonesty** [comment]
We have accepted the issues moved.

We did have to do some fixes:
1. One was not on the KB-content board.  We added it.
2. Please note that step 2 says to do the following:
> Check the comment you’ve made for the ‘Overview’, ‘Resources/Instructions’, and ‘Projects to Check’ sections of the outdated description. 
> Copy the ‘Overview’, ‘Resources/Instructions’, and ‘Projects to Check’ into the new issue description.

3. the Phase and status labels from step 8 were not followed.  We have added them

**Comment by Aditya23soni** [comment]
@fchan218  I have reviewed all the issues that we moved to Marketing and the status and Phase labels are according to the guidance.

**Comment by fchan218** [comment]
@Aditya23soni please change the status on the project board: https://github.com/hackforla/knowledgebase-content/issues/119

**Comment by fchan218** [comment]
@Aditya23soni please provide update
