### ISSUE TITLE
Migrating Revenue Guides to New Repo

### ISSUE THREAD

**Issue by Aditya23soni** [hackforla/guides#183]
### Overview
We need to move all existing guides to the new repository for guides and templates (knowledgebase-content)

### Prerequisite
You need to have 
- Manager access to the following drives
   - CoP Google Drives
   - KB-content drive
- Admin access for the repos the issues are in

### Action Items
Use the Guide below to migrate all guides related to Revenue from CoPs to knowledgebase-content.  (e.g., there might be a research guide that is relevant to product in the Revenue community of practice). 
- [x] Do steps 1-5
- [x] Add a comment below with the heading and add a link to each of the issues you moved for that CoP
```
### Guides that are ready to move for lead review
- #
```
- [x] Move this issue to the Questions/Review column on project board and add the label `ready for pm lead`
   - [ ] Message the lead in the Guides Slack channel by sending a link to the comment with the issues 
- [x] lead will sign-off if the issues are ready to move
   - [ ] once you get sign-off, you can move the issues (step 6 in the guide)
- [x] Check wikis/other resources for references to guides by numbers or names, so no links end up broken
- [x] When you are done, go to https://github.com/hackforla/guides/issues/174 and check off the dependency.  If all other dependencies are checked off already, then move that issue into the new issue approval column and add it to the team agenda https://github.com/hackforla/guides/issues/136

### Resources/Instructions
- Epic for all CoP guides moves: https://github.com/hackforla/guides/issues/169
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Repo [Revenue CoP Repo](https://github.com/hackforla/revenue)
  - Repo, Issue Tab: [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/revenue/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40)
     - Repo, Issue Tab, "Create a Guide" only issue [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/revenue/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+%22Create+a+Guide%2FTemplate%22+)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Google Drive: [Revenue (Community of Practice](https://drive.google.com/drive/folders/0AMHGjmh4EJW2Uk9PVA)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)
- Form: [Guides Migration Google Form](https://forms.gle/LixbvxuopKthEwZo9) 
- Spreadsheet: [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?usp=sharing)
- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)

**Comment by fchan218** [comment]
### Issues to check before proceeding with steps 1-5: 
check them off when approved to begin steps 1-5

- [ ] ~https://github.com/hackforla/revenue/issues/27~
- [x] https://github.com/hackforla/knowledgebase-content/issues/100
- [x] this issue is closed: https://github.com/hackforla/knowledgebase-content/issues/103

**Comment by Aditya23soni** [comment]
1. Progress: completed till step 10 in the moving guide for the Issue https://github.com/hackforla/knowledgebase-content/issues/100
2. Blockers: Step 10. The issue is not present in the new guide tracker.
3. Availability: Available 6 hours
4. ETA: N/A
5. Pictures (if necessary): N/A

**Comment by fchan218** [comment]
@Aditya23soni you can move this issue to knowledgebase content https://github.com/hackforla/knowledgebase-content/issues/103

**Comment by Aditya23soni** [comment]
> @Aditya23soni you can move this issue to knowledgebase content [hackforla/revenue#28](https://github.com/hackforla/revenue/issues/28)

Done!

**Comment by fchan218** [comment]
@Aditya23soni can you add the guide linked in one of the comments  into the resource section of the description https://github.com/hackforla/knowledgebase-content/issues/103

**Comment by Aditya23soni** [comment]
> @Aditya23soni can you add the guide linked in one of the comments into the resource section of the description [hackforla/knowledgebase-content#103](https://github.com/hackforla/knowledgebase-content/issues/103)

Done and Done

**Comment by fchan218** [comment]
@Aditya23soni Please add link to the Google Drive Folder under resources. Use to this issue for reference:
-  https://github.com/hackforla/knowledgebase-content/issues/100

This issue needs the Google Drive folder linked: 
- [x] https://github.com/hackforla/knowledgebase-content/issues/103

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni I am unable to see what specifically you have completed on this issue, and what remains, because none of the check boxes at the top of this issue are checked off. Please update the top of the issue as well as giving a status report in a comment.

**Comment by Aditya23soni** [comment]
@ExperimentsInHonesty Already migrated these two guides with Step 13/13 completed as well as the guide has been cleaned up too for you to Triage

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni Please mark off the checkboxes of what you have done at the top of this issue

**Comment by Aditya23soni** [comment]
@ExperimentsInHonesty Done. Added the "Ready for triage" label aswell
