### ISSUE TITLE
Migrating Admin Guides to New Repo

### ISSUE THREAD

**Issue by Aditya23soni** [hackforla/guides#184]
### Overview
We need to move all existing guides to the new repository for guides and templates (knowledgebase-content)

### Prerequisite
You need to have 
- Manager access to the following drives
   - CoP Google Drives
   - KB-content drive
- Admin access for the repos the issues are in

### Action Items
Use the Guide below to migrate all guides related to Admin from CoPs to knowledgebase-content.  (e.g., there might be a research guide that is relevant to product in the Admin community of practice). 
- [x] Do steps 1-5
- [ ] Add a comment below with the heading and add a link to each of the issues you moved for that CoP
```
### Guides that are ready to move for lead review
- #
```
- [ ] Move this issue to the Questions/Review column on project board and add the label `ready for pm lead`
   - [ ] Message the lead in the Guides Slack channel by sending a link to the comment with the issues 
- [x] lead will sign-off if the issues are ready to move
   - [x] once you get sign-off, you can move the issues (step 6 in the guide)
- [ ] Check wikis/other resources for references to guides by numbers or names, so no links end up broken
- [ ] When you are done, go to https://github.com/hackforla/guides/issues/174 and check off the dependency.  If all other dependencies are checked off already, then move that issue into the new issue approval column and add it to the team agenda https://github.com/hackforla/guides/issues/136

### Resources/Instructions
- Epic for all CoP guides moves: https://github.com/hackforla/guides/issues/169
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Repo [Admin CoP Repo](https://github.com/hackforla/Admin)
  - Repo, Issue Tab: [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/Admin/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+)
     - Repo, Issue Tab, "Create a Guide" only issue [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/Admin/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+%22Create+a+Guide%2FTemplate%22)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)
- Form: [Guides Migration Google Form](https://forms.gle/LixbvxuopKthEwZo9) 
- Spreadsheet: [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?usp=sharing)
- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)

**Comment by fchan218** [comment]
### Issues to check before proceeding with steps 1-5: 
check them off when approved to begin steps 1-5

- [ ] https://github.com/hackforla/admin/issues/40
- [ ] https://github.com/hackforla/admin/issues/29
- [ ] https://github.com/hackforla/admin/issues/28
- [ ] https://github.com/hackforla/admin/issues/27
- [ ] https://github.com/hackforla/admin/issues/26
- [ ] https://github.com/hackforla/admin/issues/25
- [ ] https://github.com/hackforla/admin/issues/23
- [ ] https://github.com/hackforla/admin/issues/22
- [ ] https://github.com/hackforla/admin/issues/43
- [ ] https://github.com/hackforla/admin/issues/32
- [x] https://github.com/hackforla/knowledgebase-content/issues/102
- [ ] https://github.com/hackforla/admin/issues/19
- [x] https://github.com/hackforla/knowledgebase-content/issues/101
- [ ] https://github.com/hackforla/admin/issues/33
- [ ] https://github.com/hackforla/admin/issues/35

**Comment by ExperimentsInHonesty** [comment]
leave all 1password guides where they are, and karen and I will go through them.

**Comment by ExperimentsInHonesty** [comment]
These are the two guide issue to migrate:

- https://github.com/hackforla/knowledgebase-content/issues/101
- https://github.com/hackforla/knowledgebase-content/issues/102

Rename all other guides in the repo 
Create a Workflow Guide:
e.g., `Guide: 1Password: Add Owners to the 1Password Account admin` would be renamed  `Create a Workflow Guide/Template: 1Password: Add Owners to the 1Password Account admin`
e.g., `Create a Guide/Template: How to make a pr  admin` would be renamed `Create a Workflow Guide/Template: How to make a pr  admin`
e.g., `Workflow Modeling: Google Sites admin` would be renamed `Create a Workflow Guide/Template: Google Sites admin`

**Comment by Aditya23soni** [comment]
25-10-2024
1. Progress: Moved 1/2 issues to KB
2. Blockers: Does not have a link in WIP tracker for https://github.com/hackforla/knowledgebase-content/issues/102, Step 10
3. Availability: Available 6 hours
4. ETA: By EOW
5. Pictures (if necessary): N/A

**Comment by fchan218** [comment]
@Aditya23soni Please add link to the Google Drive Folder under Resources for both the issues. Use to this issue for reference:
- https://github.com/hackforla/knowledgebase-content/issues/100

Two issues that need the folder: 
- https://github.com/hackforla/knowledgebase-content/issues/101
- https://github.com/hackforla/knowledgebase-content/issues/102

**Comment by Aditya23soni** [comment]
1. Progress: Added links to google drives in the all issues descriptions that were moved to Knowledge-based content.
2. Blockers: None
3. Availability: Available 6 hours
4. ETA: EOW
5. Pictures (if necessary): N/A
* SAME as last week*

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni I am unable to see what specifically you have completed on this issue, and what remains, because none of the check boxes at the top of this issue are checked off.  Please update the top of the issue as well as giving a status report in a comment.

**Comment by Aditya23soni** [comment]
1. Progress:Moved 2/2 issues to KB  mentioned in the comment https://github.com/hackforla/guides/issues/184#issuecomment-2422710890
2. Blockers: None
3. Availability: 20 hours
4. ETA: Done
5. Pictures (if necessary): N/A
@ExperimentsInHonesty I did not work on this issue last week as it has already completed months ago

**Comment by Rabia2219** [comment]
@fchan218 
Bonnie triaged the two issues from this epic and added milestones and placed them on the board.

**Comment by fchan218** [comment]
> [@fchan218](https://github.com/fchan218) Bonnie triaged the two issues from this epic and added milestones and placed them on the board.

thank you @Rabia2219 I have removed the "milestone: missing" labels from both issues
