### ISSUE TITLE
Migrating UI/UX Guides to New Repo

### ISSUE THREAD

**Issue by JesseTheCleric** [hackforla/guides#185]
### Overview
We need to move all existing guides to the new repository for guides and templates (knowledgebase-content)

### Prerequisite
You need to have 
- Manager access to the following drives
   - CoP Google Drives
   - KB-content drive
- Admin access for the repos the issues are in

### Action Items
Use the Guide below to migrate all guides related to UI/UX from CoPs to knowledgebase-content.  (e.g., there might be a research guide that is relevant to product in the UI/UX community of practice). 
- [ ] Do steps 1-5
- [ ] Add a comment below with the heading and add a link to each of the issues you moved for that CoP
```
### Guides that are ready to move for lead review
- #
```
- [ ] Move this issue to the Questions/Review column on project board and add the label `ready for pm lead`
   - [ ] Message the lead in the Guides Slack channel by sending a link to the comment with the issues 
- [ ] lead will sign-off if the issues are ready to move
- [ ] once you get sign-off, you can move the issue (step 6 in the guide)
- [ ] Check wikis/other resources for references to guides by numbers or names, so no links end up broken
- [ ] When you are done, go to https://github.com/hackforla/guides/issues/174 and check off the dependency.  If all other dependencies are checked off already, then move that issue into the new issue approval column and add it to the team agenda https://github.com/hackforla/guides/issues/136

### Resources/Instructions

- Epic for all CoP guides moves: https://github.com/hackforla/guides/issues/169
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Repo [UI/UX CoP Repo](https://github.com/hackforla/UI-UX)
  - Repo, Issue Tab: [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/UI-UX/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+)
     - Repo, Issue Tab, "Create a Guide" only issue [Search for guides that have not been moved to the Knowlegebase repo](https://github.com/hackforla/UI-UX/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+guide+creation%22+-project%3Ahackforla%2F40+%22Create+a+Guide%2FTemplate%22)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)
- Form: [Guides Migration Google Form](https://forms.gle/LixbvxuopKthEwZo9) 
- Spreadsheet: [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?usp=sharing)
- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
# Guides moved
- https://github.com/hackforla/knowledgebase-content/issues/140
- https://github.com/hackforla/knowledgebase-content/issues/141
- https://github.com/hackforla/knowledgebase-content/issues/139
- https://github.com/hackforla/knowledgebase-content/issues/137
- https://github.com/hackforla/knowledgebase-content/issues/138
- https://github.com/hackforla/knowledgebase-content/issues/134
- https://github.com/hackforla/knowledgebase-content/issues/135
- https://github.com/hackforla/knowledgebase-content/issues/136
- https://github.com/hackforla/knowledgebase-content/issues/132
- https://github.com/hackforla/knowledgebase-content/issues/131
- https://github.com/hackforla/knowledgebase-content/issues/133
- https://github.com/hackforla/knowledgebase-content/issues/63
- https://github.com/hackforla/knowledgebase-content/issues/62
- https://github.com/hackforla/knowledgebase-content/issues/61
- https://github.com/hackforla/knowledgebase-content/issues/47
- https://github.com/hackforla/knowledgebase-content/issues/53
- https://github.com/hackforla/knowledgebase-content/issues/54
- https://github.com/hackforla/knowledgebase-content/issues/55
- https://github.com/hackforla/knowledgebase-content/issues/56
- https://github.com/hackforla/knowledgebase-content/issues/57
- https://github.com/hackforla/knowledgebase-content/issues/78
- https://github.com/hackforla/knowledgebase-content/issues/79
- https://github.com/hackforla/knowledgebase-content/issues/80
- https://github.com/hackforla/knowledgebase-content/issues/89
- https://github.com/hackforla/knowledgebase-content/issues/112
- https://github.com/hackforla/knowledgebase-content/issues/81
- https://github.com/hackforla/knowledgebase-content/issues/121
- https://github.com/hackforla/knowledgebase-content/issues/123
- https://github.com/hackforla/knowledgebase-content/issues/124
- https://github.com/hackforla/knowledgebase-content/issues/125
- https://github.com/hackforla/knowledgebase-content/issues/126
- https://github.com/hackforla/knowledgebase-content/issues/127
- https://github.com/hackforla/knowledgebase-content/issues/128
- https://github.com/hackforla/knowledgebase-content/issues/129

**Comment by JesseTheCleric** [comment]
### Guides that are ready for lead review
Please check off when you have reviewed it.
- [x] https://github.com/hackforla/knowledgebase-content/issues/131
- [x] https://github.com/hackforla/knowledgebase-content/issues/133
- [x] https://github.com/hackforla/knowledgebase-content/issues/134

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by JesseTheCleric** [comment]
2024-10-07 Update
1. Progress: Steps 1-5 Complete on 9/37,  All 11 Steps complete on 6/37
2. Blockers: PM still learning process. Numerous errors with first issues, including not creating folders in correct locations. Received extensive assistance from PM Leads
3. Availability: 12 Hours
4. ETA: 10-21-24 End of Day
5. Pictures or links : [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?gid=334170522#gid=334170522)
</p>
</detail>

**Comment by fchan218** [comment]
### Closed issues that are moved into the knowledgebase repo 

- https://github.com/hackforla/knowledgebase-content/issues/90
- https://github.com/hackforla/knowledgebase-content/issues/91
- https://github.com/hackforla/knowledgebase-content/issues/92
-  https://github.com/hackforla/knowledgebase-content/issues/93
- https://github.com/hackforla/knowledgebase-content/issues/94
- https://github.com/hackforla/knowledgebase-content/issues/95
- https://github.com/hackforla/knowledgebase-content/issues/96
- https://github.com/hackforla/knowledgebase-content/issues/97
- https://github.com/hackforla/knowledgebase-content/issues/98
- https://github.com/hackforla/knowledgebase-content/issues/99

**Comment by fchan218** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by fchan218** [comment]
@JesseTheCleric Please make sure to link the Google Drive Folder under "Resources" for all the issues that have been moved to knowledgebase content repo. Use this as reference/example of how it should look: 
- https://github.com/hackforla/knowledgebase-content/issues/100

@fchan218 Okay, resource folders linked to each issue

**Comment by JesseTheCleric** [comment]
1. Progress: Steps 1-5 Complete on 17/37,  All 11 Steps complete on 15/37
2. Blockers: I'm still learning and updating the process (continued from last week)  Errors requiring backtracking and additional PM support eating up man-hours. Step 14 added required going over moved issues. Small details missing in documentation. Will work updating and following documentation to 100% accuracy to avoid time-consuming mistakes.
3. Availability: 6 Hours
4. ETA: 11-10-24 End of Day
5. Pictures or links : [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?gid=334170522#gid=334170522)

**Comment by ExperimentsInHonesty** [comment]
@JesseTheCleric In addition to the items above, there are two more issues that have not been addressed.  Please indicate when they are ready for lead review by adding a checkbox and linking this comment in the Slack chat for Aditya
- [x] https://github.com/hackforla/knowledgebase-content/issues/131
- [x] https://github.com/hackforla/knowledgebase-content/issues/134

**Comment by ExperimentsInHonesty** [comment]
@JesseTheCleric Sorry to hear you are feeling unwell.  When you are feeling better, please provide an update

**Comment by JesseTheCleric** [comment]
1. Progress: Steps 1-5 Complete on 25/38, All 11 Steps complete on 25/38
2. Blockers: None beyond less time available
3. Availability: 4 Hours
4. ETA: 12-06-24
5. Pictures or links : [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?gid=334170522#gid=334170522)

**Comment by JesseTheCleric** [comment]
### Guides that are ready for lead review
Please check off when you have reviewed it.

**Comment by fchan218** [comment]
@JesseTheCleric please go through UI/UX issues to see if any of the guides you have moved need to have the "drive: share with me" or "drive: shared drive" for the documents that you don't have access to - we will try to give you access for transfer

**Comment by JesseTheCleric** [comment]
@fchan218  These are the guide documents I need access too
is:issue is:open label:"CoP: UI/UX" label:"drive: shared with me"

https://github.com/hackforla/knowledgebase-content/issues?q=is%3Aissue%20is%3Aopen%20label%3A%22CoP%3A%20UI%2FUX%22%20label%3A%22drive%3A%20shared%20with%20me%22%20%20


is:issue is:open label:"CoP: UI/UX" label:"drive: shared drive"
https://github.com/hackforla/knowledgebase-content/issues?q=is%3Aissue%20is%3Aopen%20label%3A%22CoP%3A%20UI%2FUX%22%20label%3A%22drive%3A%20shared%20drive%22%20

**Comment by Aditya23soni** [comment]
- Issues with comments that I am not sure how to hide as resolved or outdated
- https://github.com/hackforla/knowledgebase-content/issues/54

**Comment by fchan218** [comment]
> * Issues with comments that I am not sure how to hide as resolved or outdated
> * [Create a Guide/Template: Glossary knowledgebase-content#54](https://github.com/hackforla/knowledgebase-content/issues/54)

No need to hide comments since this issue is actively being worked on right now.

**Comment by fchan218** [comment]
@JesseTheCleric please check off the boxes for the steps in the description that you have completed
