### ISSUE TITLE
Revise labels in UX CoP

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#37]
### Dependency
- #59 

### Overview
We need to revise labels to address when items are ready for publication and when they have published

### Action Items

- [ ] Rename the label  "place guide" to be "ready publication"
- [ ] Add new label "published"
- [ ] Revise "review guide" to be "Needs Peer Review"
- [ ] Revise all issues that refer to those labels
- [ ] Revise all templates that refer to those labels

#### UX Links
[Guide Issue Template](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=Guide%3A+Research%2C+documentation&template=template-for-making-guides.md&title=Create+a+Guide%2FTemplate%3A+%5Bname+of+item%5D)
[Guide Labels](https://github.com/hackforla/UI-UX/labels?q=guide)
[Guide Issues](https://github.com/hackforla/UI-UX/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+guide+creation%22)

Epic Issue #48

**Comment by ExperimentsInHonesty** [comment]
We are moving all the guide issues and their documents to a central location which will be accessible from a single project board
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)


And here is our guide for doing that move.

- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)
