### ISSUE TITLE
Gather Requirements: Tracker

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#43]
### Overview
We need a tracking application (either built or bought) for the guides in order to ensure the pipeline runs smoothly.

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ExperimentsInHonesty** [comment]
Requirements for a guide tracking system:
- [ ] Accessible by all guide authors to do updates (so that CoP leads don't have to do more work)
- [ ] Easy to keep updated
- [ ] Either know the status of the issue, or replace issues as a way of tracking the work done on guides
- [ ] Encourage Peer review
- [ ] Easy to identify which guide issues need leadership review
- [ ] Easy to search for guides in progress
- [ ] Easy to create new guide issues, and not duplicate 
- [ ] Identify when published
- [ ] Have a way to get suggestions for changes into the pipeline once guides are published
- [ ] Differentiate completed guides from the ones in progress
- [ ] Prompt/ remind authors of guides in progress and motivate them to complete them
- [ ] Clearly lay out each step of the system/process so authors are aware where they are and know what to anticipate
- [ ] Straightforward, uncomplicated, and require minimal admin efforts
- [ ] Easy to label guides in different categories: product, design, etc
- [ ] Information to collect
   - [ ] Name of Guide
   - [ ] Guide Authors (primary and secondary)
   - [ ] Date of creation
   - [ ] Which Community of Practice they came out of
   - [ ] Who will find them valuable (Development,  Design, Project Management,  Professional Development, Research)
- [ ] Related Templates
- [ ] Related Guides (either refer to the other guide or are a part of a larger issue together)
- [ ] Status

Current method for tracking guides:
- Issues in each repository with label systems
- Spreadsheets in some CoPs
- Spreadsheet in Guide Team Google Drive
- Various Issues in Guides Team repository for tracking guide issues that are non standard

**Comment by edwardsarah** [comment]
@ExperimentsInHonesty Does the current guides tracker suffice for this purpose? Can we close this issue?
