### ISSUE TITLE
Review Done Columns of CoPs 

### ISSUE THREAD

**Issue by carolzjy** [hackforla/guides#46]
### Overview
We need to update labels in done column of each CoP so that they reflect the recent label changes. 

### Action Items
- [ ] Add all of the links of the done columns from CoPs project board below
- [ ] look at any issues in the done columns of CoPs to see if they need labels changes
- [ ] Revise tracker with the above
- [ ] Revise tracker for Admin to add the label Add published to admin only

### Resources/Instructions
[UX](https://github.com/hackforla/UI-UX/projects/1#column-12351489)
