### ISSUE TITLE
Add new label to tracking system

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#57]
### Overview
We need to add another label to all the guide issues to accommodate Leadership Edits.

### Action Items
- [ ] Create issue for each of the CoPs to Make sure that all Guides have this extra step and label
   - [ ] Product-Management
   - [ ] UI-UX
   - [ ] Revenue
   - [ ] Engineering
   - [ ] Data Science
   - [ ] Marketing
   - [ ] Ops
   - [ ] Admin
   - [ ] Design Systems (hold off on doing this one, until Bonnie talks to Hana)

```
- [x] Present to the Hack for LA leadership team for sign off
   - [x] If the guide needs more edits Leadership team will remove the "Guide: Leadership Review" label and add the "Guide: Leadership Edits Requested" label
   - [ ] Once Author has made changes, remove the "Guide: Leadership Edits Requested" label and add the "Guide: Leadership Review" label
   - [ ] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Place Guide" label
```
- [ ] Update Tracker with new column

### Resources/Instructions
See example issue https://github.com/hackforla/UI-UX/issues/27
[Guides Audit, All Guides Tracker](https://docs.google.com/spreadsheets/d/1mO3MPGPs3fD45XI1yuVeToqROS6n4rmY8ciGjVst9sc/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
We are moving all the guide issues and their documents to a central location which will be accessible from a single project board
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)


And here is our guide for doing that move.

- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)
