### ISSUE TITLE
We Need to Update the Template for Making Guides in Each CoPs with New Labels

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/guides#59]
### Overview
We need to add new guide labels to the template for making guides in each CoPs so that they can all have a uniform standard format.

### Action Items
- [ ] Check all the CoPs to confirm that they all have a template for making guide (adding the guide templates in resources section below)
- [ ] Add a template for making guides in the CoPs that don't have one.
- [ ] Add all the new guides labels in the template.
- [ ] Update and release the dependency on the separate issues for each CoPs so that we can update all the new labels across the guide issues. 
  - [ ] UI/UX #37 
  - [ ] Product Management #47 
  - [ ] Data Science #49 
  - [ ] Marketing #50 
  - [ ] Revenue #51 
  - [ ] Dev Ops #52 
  - [ ] Engineering #53 

#### These are the new labels that we have currently identified as being missing:
- Guide: Leadership Edits Requested
- Guide: Needs Peer Review
-  Rename the label "place guide" to be "ready publication"
-  Add new label "published"
-  Revise "review guide" to be "Needs Peer Review"

### Resources/Instructions

[Product Management Issue Template](https://github.com/hackforla/product-management/blob/master/.github/ISSUE_TEMPLATE/template-for-making-guides-templates.md)

**Comment by ExperimentsInHonesty** [comment]
We are moving all the guide issues and their documents to a central location which will be accessible from a single project board
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)


And here is our guide for doing that move.

- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)
