### ISSUE TITLE
Conduct interviews with each CoP to discuss how guides fit into their process and learn about their sentiments

### ISSUE THREAD

**Issue by carolzjy** [hackforla/guides#64]
### Overview
We need to conduct interviews with CoPs to learn about their roadmap and sentiments about guides. 

### Action Items
- [ ] Create a research plan draft
  - [ ] review with Guides Team PMs
- [ ] Create a training deck
   - [ ] review deck with other researchers
- [ ] Conduct training
- [ ] Conduct interviews with CoPs
  - [ ] Engineering
  - [ ] Marketing 
  - [ ] PM
  - [ ] UI/ UX
  - [ ] Data Science
  - [ ] Revenue
  - [ ] Ops
- [ ] Discuss how guides fit into their roadmaps
- [ ] Learn about their sentiments about guides

### Resources/Instructions
[Guide: How to make a Research plan -draft ](https://docs.google.com/document/d/1lTmjiAzSwiUOFD4f4eGs0WGktaqZ6ogx_fiXhP7oR9U/edit?usp=sharing)
[See this issue for other projects research plans](https://github.com/hackforla/knowledgebase-content/issues/138)
