### ISSUE TITLE
Guide Tracker

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#70]
### Overview
We need to have a unified tracker that all guides so that we can see our numbers and increase velocity and capacity

### Action Items
- [x] Add all guide issues to the guide tracker
- [ ] Record status weekly
- [ ] Add issues here that are related

Related Issues
- [x] #59 
- [x] https://github.com/hackforla/guides/issues/57

Issues that need to be created
- [ ] Reviewing all issues in triage to get them into correct columns

### Resources/Instructions
Tracker: https://github.com/orgs/hackforla/projects/3

**Comment by ExperimentsInHonesty** [comment]
2021-11-03
Need to be Triaged: 122
Needs Relabeling: 0
Properly Labeled: 3
Needs Leadership Review: 0
Waiting for response (next meeting): 1
Waiting for response (next week): 0

The reason why all other columns are low is Triage is high

**Comment by ExperimentsInHonesty** [comment]
We are moving all the guide issues and their documents to a central location which will be accessible from a single project board
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)


And here is our guide for doing that move, which includes updating the tracker spreadsheet as the move happens.  
- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)
- Spreadsheet: [New Guide Tracker (WIP)](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?gid=334170522#gid=334170522)
